### ISSUE TITLE
data: Generate json files for 2023 JOSAA and CSAB rounds.

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#10]
Generate json files for 2023 josaa and csab rounds.

You can use tools like `csvtojson` or `csvkit` to perform such operations.

Reference - https://github.com/ksauraj/jee_counsellor/tree/master/josaa/2022/round_1

**Comment by aavvvacado** [comment]
Kindly assign  me this under iwoc 2024

**Comment by ksauraj** [comment]
> Kindly assign me this under iwoc 2024

Go ahead
