### ISSUE TITLE
webview: update ui for the created html file for displaying filtered contents.

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#11]
The created webpage is quite ugly right now, any improvement is welcomed.

![Screenshot_2024-01-11-22-49-22-34_c1ebbaff44ba152fb7f7c2e1f7129fd1~2](https://github.com/ksauraj/jee_counsellor/assets/81681419/5e779ede-744e-4f71-9d1f-7201dfe5dbbf)

You can edit your code [here](https://github.com/ksauraj/jee_counsellor/blob/8f26a5b1779bef3e1ef3fb06543d9c0234b2dc4f/tool.py#L299-L400)

**Comment by TheDarkW3b** [comment]
Assign it to me please

**Comment by YASH-YADAV-dynamo** [comment]
i would love to contribute to this issue .
Please assign me this issue

**Comment by ksauraj** [comment]
> i would love to contribute to this issue . Please assign me this issue

Yah sure, go ahead

**Comment by aavvvacado** [comment]
assign this to me

**Comment by ksauraj** [comment]
Okay
