### ISSUE TITLE
termux: find a way to run tool on termux

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#12]
All dependencies used here are available on termux ( __pandas, colorama__ )
But the main problem is to install __numpy__ ( which is used by pandas ) in termux.
If someone can make a accurate guide to make it run on termux will be very helpful.
We can also add bash script for reducing pain for new users.

**Comment by ownerofworld** [comment]
Assign it to me please

**Comment by TheDarkW3b** [comment]
Assign it to me please

**Comment by ksauraj** [comment]
> Assign it to me please

Sure, Go ahead

**Comment by TheDarkW3b** [comment]
General `numpy` installation fails as termux doesn't support NumPy, some functions required to build NumPy is unavailable as NumPy is written in C and needs to be compiled.

![numpy](https://github.com/ksauraj/jee_counsellor/assets/54339318/37afa12d-219f-4074-99bb-e6617ce74ab1)

Later on `python-numpy` is added, which is specially made for termux users. 
Similarly `python-pandas` was made which internally uses `python-numpy` but it lies under `tur-repo`.
