### ISSUE TITLE
tool: adding a about section in the tool

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#14]
In the main menu, we propose adding an **'About'** section that will showcase the current version, provide a brief overview of the tool, acknowledge contributors, and include other relevant information. This section aims to offer users a comprehensive understanding of the tool, its evolution, and the people involved in its development.

**Comment by TheDarkW3b** [comment]
Assign it to me please

**Comment by ksauraj** [comment]
> Assign it to me please

I have already assigned you a [issue](https://github.com/ksauraj/jee_counsellor/issues/12), after finishing that you can work on this too, But for now I will not be able to assign this to you.

**Comment by Tholkappiar** [comment]
#### Can I work on this Issue , if so assign this issue to me !

**Comment by ksauraj** [comment]
> #### Can I work on this Issue , if so assign this issue to me ! @ksauraj

Yah sure, I'm assigning it to you.

**Comment by Tholkappiar** [comment]
Hello @ksauraj , i have added required amount of details , but for the version thing can you give the info about version things !
Added the contributors by the Gitpython library !
![Screenshot from 2024-01-16 10-46-32](https://github.com/ksauraj/jee_counsellor/assets/114584730/36635052-1a33-493a-a778-0212e2af8393)

**Comment by ksauraj** [comment]
@Tholkappiar I really like your efforts but I want you to implement these changes
- Try not adding extra dependencies, like I can understand you need `gitpython` for checking contribution list in automation but we can add it manually via commit or an action script while release of new version everytime.
- Secondly, After checking about section we should have a option to return back to main menu, kinda loop in short. 
- And at last utilise clear screen function and print ascii art which will match the overall theme of the tool.

**Comment by Tholkappiar** [comment]
Okay , so for the contributors section , which one ok for you manual adding or you can add the action script and configure it ? I will do the remaining changes as referenced , waiting for you response , thank you !

**Comment by ksauraj** [comment]
> Okay , so for the contributors section , which one ok for you manual adding or you can add the action script and configure it ? I will do the remaining changes as referenced , waiting for you response , thank you !

For now you continue with manual adding, in future we will be adding a script before new release of tool, so for now you can just add my name in "Author" and let the contributor section be empty or just add my name in contributor section too.

**Comment by Tholkappiar** [comment]
And for version ?

**Comment by ksauraj** [comment]
> And for version ?

Just add version, you can check it [here](https://github.com/ksauraj/jee_counsellor/releases)

Also make sure to colorize stuffs 🎨.

**Comment by Tholkappiar** [comment]
yeah okay , there are n number of versions based on the OS ! which should i choose or display all like key value pairs for the OS with versions ?

**Comment by ksauraj** [comment]
> yeah okay , there are n number of versions based on the OS ! which should i choose or display all like key value pairs for the OS with versions ?

Its `v2.0.2` overall

**Comment by Tholkappiar** [comment]
I have made the changes , can i push the changes !

[Screencast from 16-01-24 01:19:06 PM IST.webm](https://github.com/ksauraj/jee_counsellor/assets/114584730/d4bff7b3-67e3-4deb-86a3-b2589aa94614)

**Comment by ksauraj** [comment]
Seems fine, make a PR.
