### ISSUE TITLE
tool: adding an option to exit from main menu of tool. 

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#18]
I iust realised we don't have option for exiting from tool from main menu, We should have one.
![Screenshot_2024-01-16-18-13-27-65_84d3000e3f4017145260f7618db1d683~2](https://github.com/ksauraj/jee_counsellor/assets/81681419/1cc10e16-1564-40f7-beaa-67c81e7059d6)

This looks ugly, we must fix it by adding option for exiting from tool.

**Comment by 29deepanshutyagi** [comment]
i want to work on this issue ,kindly assign me this issue @ksauraj

**Comment by sarvinshrivastava** [comment]
I also want to work on this, can u too assign this issue to me?

**Comment by ksauraj** [comment]
> I also want to work on this, can u too assign this issue to me?

Thanks for your interest, @sarvinshrivastava, but this issue has already been assigned to @29deepanshutyagi.

@29deepanshutyagi, please confirm if you are still working on this, or should I assign it to @sarvinshrivastava ?

**Comment by ksauraj** [comment]
@sarvinshrivastava Are you still interested in this? I can assign it to you now as there is no response from @29deepanshutyagi

**Comment by sarvinshrivastava** [comment]
Yes i am interested

**Comment by ksauraj** [comment]
> Yes i am interested

Okay, I'm assigning this to @sarvinshrivastava . I'm sorry @29deepanshutyagi , but you are no longer assigned to this due to inactivity.
