### ISSUE TITLE
Tool fails due to permission elevation

### ISSUE THREAD

**Issue by TheDarkW3b** [ksauraj/jee_counsellor#24]
When opening an HTML file through Termux on an Android device, you may encounter permission issues related to the Termux sandbox environment and the security policies of the Chrome browser. 

Termux operates within a restricted environment on Android, and certain actions that require broader permissions are restricted.

So this line eventually fails(it reaches the last case in android as both above conditions becomes false):
![image](https://github.com/ksauraj/jee_counsellor/assets/54339318/d8f8b88e-1771-4e6a-97e2-b763f91595bd)
***
Due to permission, one just can't hit the following url
`content://com.termux.files/data/data/com.termux/files/home/jee_counsellor/output/<fileName>.html`

<img src="https://github.com/ksauraj/jee_counsellor/assets/54339318/86b6e1d8-bb3c-4183-906f-d15b97a43ee8" width="1000" height="500">

***
**Security Policies of Chrome**: 
* The Chrome browser, like other modern browsers, enforces strict security policies, especially when it comes to opening local files. Chrome's security model limits the ability of web pages to access local resources to prevent potential security vulnerabilities and attacks.
***
**Solution could be**:
* Move file to allowed location, but it can lead to exception and often requires root privileges to write in some destination.
* Use a Simple HTTP Server: Start a simple HTTP server in Termux using Python or another tool. This way, you can access the HTML file through a local web server, and Chrome's security policies may allow it.

**Comment by ksauraj** [comment]
Actually you can move files to `~/storage/shared/some_dir` .
For this you just need to give termux storage permission via this command `termux-setup-storage`
![Screenshot_2024-01-23-23-10-49-05_84d3000e3f4017145260f7618db1d683](https://github.com/ksauraj/jee_counsellor/assets/81681419/487716bc-1edd-44d5-95ee-d3f9a325f3fd)

Trying doing this and most probably it  will work.

**Comment by TheDarkW3b** [comment]
`termux-setup-storage` doesn't work for me.
I did it by implementing a local webserver.
If you agree assign it to me under `iwoc2024`

**Comment by TheDarkW3b** [comment]
I think it should be labelled as hard.
Finding the issue is a work in itself  and then looking/implementing a optimized fix.
Termux users can employ to achieve similar results without introducing new complexities such as allowing for storage and haven't used any third party library(which seems a lot of concern for you).
Please analyse the PR and let me know

**Comment by ksauraj** [comment]
> I think it should be labelled as hard. Finding the issue is a work in itself and then looking/implementing a optimized fix. Termux users can employ to achieve similar results without introducing new complexities such as allowing for storage and haven't used any third party library(which seems a lot of concern for you). Please analyse the PR and let me know

You are right, I labelled it as hard. Sorry for inconvenience caused.
