### ISSUE TITLE
webpage: ugly interface while "sharing" the generated html file

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#36]
Since the generated html depends on the different icons present inside `assets` folder, so while sharing only the html file, these icons won't be loaded making it uglier :((

**Comment by aavvvacado** [comment]
Please assign this issue to me ill fix

**Comment by ksauraj** [comment]
Sure, assigning this to you

**Comment by ksauraj** [comment]
Also please discuss about the approach you will consider to fix this...

**Comment by aavvvacado** [comment]
Sure
