### ISSUE TITLE
tool:remove the extra text that looks ugly in progress bar

### ISSUE THREAD

**Issue by shaluchan** [ksauraj/jee_counsellor#38]
![Screenshot_20241019_171539](https://github.com/user-attachments/assets/9671dc13-56b9-4297-964f-099f39606dc4)

**Comment by ksauraj** [comment]
Ahh! you are right, it's really looking ugly, we must remove it as its unwanted in my opinion...

**Comment by shaluchan** [comment]
I wan to work on it... please assign this issue to me

**Comment by ksauraj** [comment]
Sure
