### ISSUE TITLE
josaa: add data for josaa 2024 counselling

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#40]
You can use [this tool](https://www.convertcsv.com/html-table-to-csv.htm) for extracting table data from official site...

Make sure you add data for all rounds in the same fashion as it exists now..
```
josaa/2024/round_1/ranks_all.csv
josaa/2024/round_1/ranks_gftis.csv
josaa/2024/round_1/ranks_iits.csv
josaa/2024/round_1/ranks_iiits.csv
josaa/2024/round_1/ranks_nits.csv
````

These are the files to be added for all given round... 
Make sure to use multiple commits for the same

I'm attaching a video for reference for creating csv files...

https://github.com/user-attachments/assets/5454df5a-ff17-4437-a098-70f8aaf41f5a

**Comment by aavvvacado** [comment]
please assign that to me

**Comment by ksauraj** [comment]
Sure, go ahead
