### ISSUE TITLE
csab: add data for csab 2024 rounds

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#41]
You can use [this tool](https://www.convertcsv.com/html-table-to-csv.htm) for extracting table data from official site...

Make sure you add data for all rounds in the same fashion as it exists now..
```
csab/2024/round_1/ranks_all.csv
csab/2024/round_1/ranks_gftis.csv
csab/2024/round_1/ranks_iiits.csv
csab/2024/round_1/ranks_nits.csv
````

These are the files to be added for all given round... 
Make sure to use multiple commits for the same

I'm attaching a video for reference for creating csv files...

https://github.com/user-attachments/assets/5454df5a-ff17-4437-a098-70f8aaf41f5a

**Comment by aavvvacado** [comment]
I would like to work on it kindly assign  me this

**Comment by ksauraj** [comment]
Sure, I'm assigning this to you
