### ISSUE TITLE
output: add option to clean output dir in the main menu of tool

### ISSUE THREAD

**Issue by ksauraj** [ksauraj/jee_counsellor#42]
I just noticed after testing my tool many times, i was having around 100+ html files in my output directory... So we should add option in tool itself to clean the output directory...

We can simply just add option to clean output directory in the main menu of the tool... which will delete all html files in the output dir, we should add confirmation before deleting all files...

**Comment by shaluchan** [comment]
pls assign this issue to me

**Comment by lakshita10341** [comment]
can u assign me this issue

**Comment by ksauraj** [comment]
Hi @shaluchan and @lakshita10341! I appreciate both of your enthusiasm for this issue. Since I can only assign it to one person and @shaluchan has already been assigned two previous issues, I will assign this one to @lakshita10341. Thank you both for your understanding and contributions!

**Comment by shaluchan** [comment]
No problem

**Comment by lakshita10341** [comment]
#47
please review the PR

**Comment by ksauraj** [comment]
Yah, I'm reviewing it

**Comment by ksauraj** [comment]
Thanks @lakshita10341 for awesome work : ) )
